---
title: "Defects"
author: sheli and nanav
date: June 4, 2018
output:
  word_document: default
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE,echo=FALSE}
library(knitr)
library(fitdistrplus)
library(magrittr)
```
--------------------------------------A-D defects ----------------------------------------------------
#The Data of the A-D defects

```{r}
filePathAD <- choose.files()
tableAD <- read.csv(filePathAD,header=FALSE)
```

## 1.  Empirical Data
```{r}
defectsAD <- tableAD$V2
boxplot(defectsAD)
```


## 2. First Impressions 
```{r}
par (mfrow = c(1,3))
plot  (defectsAD, ylab= "sample values")
hist(defectsAD, ylab="Frequency ") # histogram (right graph)
boxplot(defectsAD)

```

## 3. Fit a known distribution 
from the hist we suspect it fits to normal distribution - we chose to use the GOF - KS.

```{r}
normalFit <- fitdist(defectsAD, "norm")
summary(normalFit) # summary function displays the results
plotdist(defectsAD,"norm",para=list(mean=normalFit$estimate[1],sd=normalFit$estimate[2])) 
print(normalFit)
```

## 4. Perform Goodness of Fit tests on fitted distribution
statisticlly test the hypothesis with GOF
```{r}
normGof <- gofstat(normalFit)%>%print()
normGof$kstest%>%print()
```

##5. estimation
```{r}
normalFit$estimate[1]
normalFit$estimate[2]
```

-----------------------------------------------E-J defects-----------------------------------------

```{r}
filePathAD <- choose.files()
tableEJ <- read.csv(filePathAD,header=FALSE)
```

## 1.  Empirical Data
```{r}
defectsEJ <- tableEJ$V2

```

```{r}
boxplot(defectsEJ)
```

removal of exceptions : 
we chose to remove only exceptions above 570 minutes who seems to us that they was exeptions and does not represent reality.
```{r}
out<-which(defectsEJ %in% boxplot.stats(defectsEJ)$out)
print(out)

```
```{r}
remove <- c(695.1138086, 629.0999128, 577.2711611, 829.9644307, 622.616411)
 defectsEJ_new <-   defectsEJ [!defectsEJ %in% remove]
boxplot(defectsEJ_new)
```


## 2. First Impressions 
```{r}
par (mfrow = c(1,3))
plot  (defectsEJ_new, ylab= "sample values")
hist( defectsEJ_new, ylab="Frequency ") # histogram (right graph)
```

## 3. Fit a known distribution 
from the hist we suspect it fits to exp.  

```{r}
expFit <- fitdist(defectsEJ_new, "exp")
summary(expFit) # summary function displays the results
plotdist(defectsEJ_new,"exp",para=list(expFit$estimate[1]) )
print(expFit)
```

## 4. Perform Goodness of Fit tests on fitted distribution
statisticlly test the hypothesis with GOF
```{r}
expGof <- gofstat(expFit)%>%print()
expGof$kstest%>%print()

```



##5. estimation
```{r}
expFit$estimate[1]

```

